export const languages = {
  English: "en",
  Hindi: "hi",
  German: "de",
  French: "fr",
  Spanish: "es",
  Italian: "it",
//   portuguese: "pt",
  Russian: "ru",
  Japanese: "ja",
  Korean: "ko",
    //   chineseSimplified: "zh-cn",
    //   chineseTraditional: "zh-tw",
    //   arabic: "ar",
 
//   urdu: "ur",
//   turkish: "tr",
//   dutch: "nl",
//   polish: "pl",
//   swedish: "sv",
//   danish: "da",
//   finnish: "fi",
//   norwegian: "no",
//   thai: "th",
//   vietnamese: "vi",
//   indonesian: "id",
//   malay: "ms",
//   greek: "el",
//   hebrew: "he",
//   czech: "cs",
//   romanian: "ro",
//   hungarian: "hu",
//   ukrainian: "uk",
//   persian: "fa",
//   sinhala: "si",
//   nepali: "ne",
//   swahili: "sw",
//   filipino: "tl",
};